#!/bin/bash
. "${HOME}/.cache/wal/colors.sh"

# ██████╗  █████╗ ███╗   ██╗███████╗██╗         ██████╗  █████╗ ██████╗ 
# ██╔══██╗██╔══██╗████╗  ██║██╔════╝██║         ██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝███████║██╔██╗ ██║█████╗  ██║         ██████╔╝███████║██████╔╝
# ██╔═══╝ ██╔══██║██║╚██╗██║██╔══╝  ██║         ██╔══██╗██╔══██║██╔══██╗
# ██║     ██║  ██║██║ ╚████║███████╗███████╗    ██████╔╝██║  ██║██║  ██║
# ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝╚══════╝    ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝

num_mon=$(bspc query -M | wc -l)
while read -r line ; do
	case $line in
		C*)
			# HORA
			hora="%{A:st -e calcurse:}${line#?}%{A}"
			;;
		D*)
			# FECHA
			fecha="%{A:st -e calcurse:}${line#?}%{A}"
			;;
		T*)
			# TUTILO DE VENTANA
			titulo="${line#?}"
			;;
		N*)
			# CONEXIONES        
			if [ ${line#??} = wlan0 ]
			then
			icono_redes="%{F$color2}%{A:st -e nmtui:}%{A}"
			elif [ ${line#??} = enp0s25 ]
			then
			icono_redes="%{F$color2}%{A:st -e nmtui:}%{F$color7} Red%{A}"
						else
			icono_redes="%{F$color2}%{A:st -e nmtui:}%{F$color7} Red%{A}"
			fi
			;;
		VI*)
			# ICONO DE VOLUMEN
			if [ ${line#??} = on ]
			then
			icono_volumen="%{F$color2}%{A:st -e alsamixer:}%{A}"
			else
			icono_volumen="%{F$color2}%{A:st -e alsamixer:}%{A}"
			fi
			;;
		VP*)
			# PORCENTAJE DE VOLUMEN
			volumen_porcentaje="%{F$color7}${line#??}%"
			;;
		BP*)
			# CARGA DE BATERIA 
			bateria_porcentaje="${line#??}"
			if [ $bateria_porcentaje -lt "10" ]
			then
			icono_bateria="%{F$color2}"
			elif [ $bateria_porcentaje -lt "20" ]
			then
			icono_bateria="%{F$color2}"
			elif [ $bateria_porcentaje -lt "50" ]
			then
			icono_bateria="%{F$color2}"
			elif [ $bateria_porcentaje -lt "90" ]
			then
			icono_bateria="%{F$color2}"
			else
			icono_bateria="%{F$color2}"
			fi
			bateria_porcentaje="%{F$color7}$bateria_porcentaje%"
			;;
		BU*)
			# ESTADO DE BATERIA
			if [ ${line#??} = Charging ]
			then
			icono_cargando="%{F$color2}"
			elif [ ${line#??} = "Full" ]
			then
			icono_cargando="%{F$color2}"
			elif [ ${line#??} = Unknown ]
			then
			icono_cargando="%{F$color2}"
			else
			icono_cargando=""
			fi
			;;			
 		X*)
			# ICONOS
			icono_brillo="%{F$color2}"
			icono_temperatura="%{F$color2}"
			icono_play="%{F$color2}%{A:mpc play:}%{A}"
			icono_power="%{F$color2}%{A:apagado:}%{A}"
			icono_ram="%{F$color2}%{A:st -e htop:}%{A}"
			icono_menu="%{F$color2}%{A:programas:}%{A}"
			icono_mpc_pausa="%{F$color2}%{A:mpc pause:}%{A}"
			icono_mpc_anterior="%{F$color2}%{A:mpc prev:}%{A}"
			icono_mpc_siguiente="%{F$color2}%{A:mpc next:}%{A}"
			icono_microfono="%{F$color2}%{F$color2}%{A:st -e alsamixer:}%{A}"
			icono_clima="%{F$color2}%{A:setsid st -e less -Srf "/tmp/clima":}%{A}"
#			icono_stop="%{F$color2}%{A:mpc stop:}%{A}"
#			icono_lluvia="%{F$color2}%{A:mpc stop:}%{A}"
#			icono_wifi="%{F$color2}%{A:st -e nmtui:}%{A}"
#			icono_ramdom="%{F$color2}%{A:mpc ramdom:}%{A}"
#			icono_temp_alta="%{F$color2}%{A:setsid st -e less -Srf "/tmp/clima":}%{A}"%{F$color2}"
#			icono_temp_baja="%{F$color2}%{A:setsid st -e less -Srf "/tmp/clima":}%{A}"%{F$color2}"
#			icono_spotify_pausa="%{F$color2}%{A:dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause:}%{A}"
#			icono_spotify_anterior="%{F$color2}%{A:dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous:}%{A}"
#			icono_spotify_siguiente="%{F$color2}%{A:dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next:}%{A}"
			# BANDEJA SISTEMA
			brillo="%{F$color7}$(xbacklight | sed 's/\..*/%/')"
			temp_cpu="%{F$color7}$(temp | awk '{print $1-0"°"}')"
			ram_uso="%{F$color7}$(free -h --kilo | awk 'NR==2 { print $3}')"
			clima_simple="%{F$color7}$(awk '{print $2-+-c"°"}' /tmp/climasimple)"
			microfono="%{F$color7}$(amixer get Capture | awk -F'[][]' 'END{ print $2 }')"
			musica_mpc="%{F$color7}%{A:st -e ncmpcpp:}$(mpc current -f '[%title% - %artist%|%file%] ')%{A}"
			wifi_nivel="%{F$color7}$(cat /proc/net/wireless | awk 'NR==3 {printf "%0.0f%%\n", $3/70*100}')"
#			essid="%{F$color7}$(essid)"
#			horas="%{F$color7}$(clock | awk '{print $2}')"
#			kernel="%{F$color7}$(uname -a | awk '{ print $1" "$3" "$8 }')"
#			uso_cpu="%{F$color7}$(top -bn1 | grep "Cpu" | awk 'NR==1 {print $2}')"
#			ram="%{F$color7}$(free | grep Mem | awk '{printf("%.f%\n",$3/$2 * 100.0)}')"
#			teclado="%{F$color7}$(setxkbmap -query | grep layout | tr -s ' ' | cut -d ' ' -f2)"
#			lluvia="%{F$color7}$(sed '16q;d' "/tmp/clima" | grep -wo "[0-9]*%" | sort -rn | sed "s/^/ /g;1q" | tr -d '\n')"
#			temp_baja="%{F$color7}$(sed '13q;d' "/tmp/clima" | grep -o "m\\([-+]\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print $1"°"}')"
#			temp_alta="%{F$color7}$(sed '13q;d' "/tmp/clima" | grep -o "m\\([-+]\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print $2"°"}')"
#			spotify_artista="%{F$color7}$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | sed -nr '/xesam:artist"/,+2s/^ +string "(.*)"$/\1/p' | tail -1 | awk '{print $1" "$2" "$3" "$4 "-  "}')"
#			spotify_titulo="%{F$color7}$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | sed -nr '/xesam:title"/,+2s/^ +variant +string "(.*)"$/\1/p' | tail -1 | awk '{print $1" "$2" "$3" "$4" "$5" "$7" "$8}')"
#			spotify_album="%{F$color7}$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | sed -nr '/xesam:album"/,+2s/^ +variant +string "(.*)"$/\1/p' | tail -1)
#			panel_spotify="%{F$color7}${spotify_artista}${spotify_titulo}"
			panel_mpc="${icono_mpc_anterior}  ${icono_mpc_pausa}  ${icono_mpc_siguiente}   ${musica_mpc}"
			bandeja="${icono_clima} ${clima_simple}  ${icono_ram} ${ram_uso}  ${icono_microfono} ${microfono}  ${icono_volumen} ${volumen_porcentaje}  ${icono_brillo} ${brillo}  ${icono_temperatura} ${temp_cpu}  ${icono_cargando} ${icono_bateria} ${bateria_porcentaje}  ${icono_redes} ${wifi_nivel}  ${icono_power}  "
			;;
		W*)
			# BSPWM ESCRITORIOS
			escritorios=
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
			item=$1
			name=${item#?}
			case $item in
				[mM]*)
					case $item in
						m*)
							# ESCRITORIO OCUPADO NO SELECCIONADO
							FG=$color7
							on_focused_monitor=
							;;
						M*)
							# ESCRITORIO ACTIVO
							FG=$color7
							on_focused_monitor=1
							;;
							esac
							[ $num_mon -lt 2 ] && shift && continue
							escritorios="${escritorios}%{F$color7}%{A:bspc monitor -f ${name}:} ${name} %{A}%{F-}"
							;;
							[fFoOuU]*)
							case $item in
						f*)
							# ESCRITORIO VACIO NO SELECIONADO
							FG=$color7
							UL=#dd181818
							;;
						F*)
							if [ "$on_focused_monitor" ] ; then
							# ESCRITORIO VACIO SELECIONADO
							FG=$color7
							UL=$color7
							else
							# ESCRITORIO VACIO NO SELECIONADO
							FG=$color7
							UL=$color7
							fi
							;;
						o*)
							# ESCRITORIO OCUPADO NO SELECCIONADO
							FG=$color7
							UL=#dd181818
							;;
						O*)
							if [ "$on_focused_monitor" ] ; then
							# ESCRITORIO OCUPADO SELECIONADO
							FG=$color7
							UL=$color7
							else
							# ESCRITORIO OCUPADO SELECIONADO
							FG=$color7
							UL=$color7
							fi
							;;
						u*)
							# ESCRITORIO PARPADEANTE URGENTE
							FG=#FF0000
							UL=#FF0000
							;;
						U*)
							if [ "$on_focused_monitor" ] ; then
							FG=$color7
							UL=#dd181818
							else
							FG=$color7
							UL=#dd181818
							fi
							;;
						esac
						escritorios="${escritorios}%{F${FG}}%{U${UL}}%{+u}%{A:bspc desktop -f ${name}:} ${name} %{A}%{F-}%{-u}"
						;;
					[LTG]*)
						# LAYOUT MODO DE VENTANAS EN UNA LETRA O DOS
						escritorios="${escritorios}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}  ${icono_menu} ${escritorios}  ${panel_mpc}%{c}${fecha}${hora}%{r}${bandeja}"
done