#! /bin/sh
. "${HOME}/.cache/wal/colors.sh"

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝

#_______________CONFIGURACION DE 1 Y 2 MONITORES_____________

#bspc monitor -d 1 2 3 4 5 6 7 8 9
#bspc monitor -d • • • • • • • • • •
bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor LVDS1 -d 6 7 8 9
#bspc monitor HDMI3 -d 1 2 3 4 5

#___________________BORDES, COLORES Y REGLAS_________________

bspc config presel_feedback_color 	"$color2"
bspc config focused_border_color	"$color2"
bspc config directional_focus_tightness low
bspc config merge_overlapping_monitors true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config automatic_scheme longest_side
bspc config focused_frame_opacity 0.05
bspc config normal_frame_opacity 1.0
bspc config window_gap		15
bspc config border_width	3
bspc config top_padding		0
bspc config split_ratio   	0.50

#____________REGLAS DE COMPORTAMIENTO DE VENTANAS____________

bspc rule -a Pavucontrol state=tiled rectangle=600x400+0+0 center=on
bspc rule -a youtube-dl state=tiled rectangle=800x500+0+0 center=on
bspc rule -a chromium state=tiled rectangle=800x500+0+0 center=on
bspc rule -a firefox state=tiled rectangle=800x500+0+0 center=on
bspc rule -a Pcmanfm state=tiled rectangle=800x500+0+0 center=on
bspc rule -a Surf state=tiled rectangle=800x500+0+0 center=on
bspc rule -a ytdl state=tiled rectangle=800x500+0+0 center=on
bspc rule -a Sxiv state=tiled rectangle=800x500+0+0 center=on
bspc rule -a mpv state=tiled rectangle=800x500+0+0 center=on
bspc rule -a St state=tiled rectangle=800x500+0+0 center=on
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a libreoffice state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

#____________________ARRANQUE DEL SISETMA_____________________

export SUDO_ASKPASS="$HOME/.config/bspwm/scripts/menupass"
export PATH="${PATH}:$HOME/.config/bspwm/scripts/"
export PATH="${PATH}:$HOME/.config/lemonbar"
export PATH="${PATH}:$HOME/.config/bspwm/"
export BROWSER=chromium
export READER=zathura
export TERMINAL=st
export EDITOR=nvim
curl -sf "wttr.in/VER?format=1" > /tmp/climasimple &
curl -sf "wttr.in/VER?lang=es" > /tmp/clima &
wal -i "$(< "${HOME}/.cache/wal/wal")"
xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null
xrdb -merge ~/.Xresources
xset r rate 300 50 &
recargardunst &
#devilspie -a &
pkill -9 panel
xset b off &
unclutter &
#xcompmgr &
picom &
panel &
sxhkd &
mpd &

