#! /bin/sh


# En caso de moficar las prefrencias y software predeterminadas, editar el archivo .local/bin/cargar_preferencias
. $HOME/.local/bin/cargar_preferencias


# Comentar la siguiente linea en caso de no usar PYWAL.
#. $HOME/.cache/wal/colors.sh


# Modifique elementos del arranque (opcional), editar el archivo .local/bin/auto_arranque
. $HOME/.local/bin/auto_arranque


# Ajustes de colores y modos de layouts.
bspc config presel_feedback_color 	"$color2"
bspc config focused_border_color	"$color2"
bspc config directional_focus_tightness low
bspc config merge_overlapping_monitors true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config automatic_scheme longest_side
bspc config focused_frame_opacity 0.05
bspc config normal_frame_opacity 1.0
bspc config window_gap		0
bspc config border_width	1
bspc config top_padding		0
bspc config split_ratio   	0.50


# Reglas de como y donde se abren ciertas apps.
bspc rule -a Pavucontrol state=tiled rectangle=600x400+0+0 center=on
bspc rule -a youtube-dl state=tiled rectangle=800x500+0+0 center=on
bspc rule -a Chrome state=tiled rectangle=800x500+0+0 center=on
bspc rule -a qutebrowser state=tiled rectangle=800x500+0+0 center=on
bspc rule -a leafpad state=tiled rectangle=800x500+0+0 center=on
bspc rule -a Leafpad state=tiled rectangle=800x500+0+0 center=on
bspc rule -a Navigator state=tiled rectangle=800x500+0+0 center=on
bspc rule -a Firefox state=tiled rectangle=800x500+0+0 center=on
bspc rule -a Pcmanfm state=tiled rectangle=800x500+0+0 center=on
bspc rule -a Surf state=tiled rectangle=800x500+0+0 center=on
bspc rule -a ytdl state=tiled rectangle=800x500+0+0 center=on
bspc rule -a Sxiv state=tiled rectangle=800x500+0+0 center=on
bspc rule -a mpv state=tiled rectangle=800x500+0+0 center=on
bspc rule -a Mpv state=tiled rectangle=800x500+0+0 center=on
bspc rule -a St state=tiled rectangle=800x500+0+0 center=on
bspc rule -a XTerm state=tiled rectangle=800x500+0+0 center=on
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a libreoffice state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
