#!/bin/sh

#DEFINIR ANCHO Y NUMERO DE LINEAS
menu_alto_lineas=10
menu_ancho=200
monitor_ancho=$(xrandr | awk '/*/ {print $1}' | cut -c 1-4)
monitor_alto=$(xrandr | awk '/*/ {print $1}' | cut -c 6-9)
#ALINEAR A LA DERECHA ARRIBA
XX=$(( $monitor_ancho - $menu_ancho -5 ))
YY=$(( 25 ))
#ALINEADO A LA IZQUIERA ARRIBA
#XX=0
#YY=25
#ALINEADO AL CENTRO
#menu_alto_pixeles=$(( $menu_alto_lineas * 10 ))
#menu_mitad_ancho=$(( $menu_ancho / 2 ))
#XX=$(( $monitor_ancho / 2 - $menu_mitad_ancho ))
#YY=$(( $monitor_alto / 2 - $menu_alto_pixeles ))

reload_bspwm="bspc wm -r"
reload_sxhkd="pkill -USR1 -x sxhkd"
reb="reboot"
shut="poweroff"
logout="killall panel;bspc quit"

cmds="\
          Bloquear	slock
        Cerrar Sesion	${logout}
        Recargar BSPwm	${reload_bspwm}
        Recargar Sxhkd	${reload_sxhkd}
         Reinciar PC	${reb}
         Apagar PC	${shut}"

choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu -w $menu_ancho -x $XX -y $YY)" || exit 1

action=$(echo "$cmds" | grep "^$choice	" | cut -d '	' -f2)

IFS=';' read -ra com <<< "$action"

for i in "${com[@]}"
do
$i
done
