#!/bin/sh

#DEFINIR ANCHO Y NUMERO DE LINEAS
menu_alto_lineas=25
menu_ancho=800
monitor_ancho=$(xrandr | awk '/*/ {print $1}' | cut -c 1-4)
monitor_alto=$(xrandr | awk '/*/ {print $1}' | cut -c 6-9)
#ALINEAR A LA DERECHA ARRIBA
#XX=$(( $monitor_ancho - $menu_ancho -5 ))
#YY=$(( 25 ))
#ALINEADO A LA IZQUIERA ARRIBA
#XX=0
#YY=25
#ALINEADO AL CENTRO
menu_alto_pixeles=$(( $menu_alto_lineas * 10 ))
menu_mitad_ancho=$(( $menu_ancho / 2 ))
XX=$(( $monitor_ancho / 2 - $menu_mitad_ancho ))
YY=$(( $monitor_alto / 2 - $menu_alto_pixeles ))

find ~/ | sed 's/ /\\ /g' | sort -f | dmenu -i -p "Buscar archivos:" -l $menu_alto_lineas -w $menu_ancho -x $XX -y $YY | xargs xdg-open