#!/bin/sh

#DEFINIR ANCHO Y NUMERO DE LINEAS HORIZONTALES
menu_alto_lineas=10
menu_ancho=350
#MEDIDAS DE MONITOR NO TOCAR
monitor_ancho=$(cat /tmp/resoluciones | awk 'NR==2 {print}')
monitor_alto=$(cat /tmp/resoluciones | awk 'NR==3 {print}')
#ALINEAR A LA DERECHA ARRIBA
XX=$(( $monitor_ancho - $menu_ancho - 2 ))
YY=$(( 25 ))
#ALINEADO A LA IZQUIERA ARRIBA
#XX=0
#YY=25
#ALINEADO AL CENTRO
#menu_alto_pixeles=$(( $menu_alto_lineas * 10 ))
#menu_mitad_ancho=$(( $menu_ancho / 2 ))
#XX=$(( $monitor_ancho / 2 - $menu_mitad_ancho ))
#YY=$(( $monitor_alto / 2 - $menu_alto_pixeles ))

case "$(printf "Selecione el area\\nVentana activa\\nToda la pantalla\\nSelecionar area (copiar)\\nVentana activa (copiar)\\nToda la pantalla (copiar)" | dmenu -l $menu_alto_lineas -w $menu_ancho -x $XX -y $YY -i -p "Selecione el tipo de captura:")" in
	"Selecione el area") maim -m 1 -s area-seleccionada-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"Ventana activa") maim -m 1 -i "$(xdotool getactivewindow)" ventana-activa-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"Toda la pantalla") maim -m 1 captura-pantalla-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"Selecionar area (copiar)") maim -m 1 -s | xclip -selection clipboard -t image/png ;;
	"Ventana activa (copiar)") maim -m 1 -i "$(xdotool getactivewindow)" | xclip -selection clipboard -t image/png ;;
	"Toda la pantalla (copiar)") maim -m 1 | xclip -selection clipboard -t image/png ;;
esac
