#!/bin/sh

#DEFINIR ANCHO Y NUMERO DE LINEAS HORIZONTALES
menu_alto_lineas=10
menu_ancho=400
#MEDIDAS DE MONITOR NO TOCAR
monitor_ancho=$(cat /tmp/resoluciones | awk 'NR==2 {print}')
monitor_alto=$(cat /tmp/resoluciones | awk 'NR==3 {print}')
#ALINEAR A LA DERECHA ARRIBA
XX=$(( $monitor_ancho - $menu_ancho - 2 ))
YY=$(( 25 ))
#ALINEADO A LA IZQUIERA ARRIBA
#XX=0
#YY=25
#ALINEADO AL CENTRO
#menu_alto_pixeles=$(( $menu_alto_lineas * 10 ))
#menu_mitad_ancho=$(( $menu_ancho / 2 ))
#XX=$(( $monitor_ancho / 2 - $menu_mitad_ancho ))
#YY=$(( $monitor_alto / 2 - $menu_alto_pixeles ))


unmountusb() {
	[ -z "$drives" ] && exit
	chosen="$(echo "$drives" | dmenu -l $menu_alto_lineas -w $menu_ancho -x $XX -y $YY -i -p "¿Que unidad desea desmontar?")" || exit 1
	chosen="$(echo "$chosen" | awk '{print $1}')"
	[ -z "$chosen" ] && exit
	sudo -A umount "$chosen" && notify-send "💻 USB desmontando" "$chosen desmontado."
	}

unmountandroid() { \
	chosen="$(awk '/simple-mtpfs/ {print $2}' /etc/mtab | dmenu -l $menu_alto_lineas -w $menu_ancho -x $XX -y $YY -i -p "¿Que dispositivo desea desmontar?")" || exit 1
	[ -z "$chosen" ] && exit
	sudo -A umount -l "$chosen" && notify-send "🤖 Desmontaje de Android" "$chosen desmontada."
	}

asktype() { \
	choice="$(printf "USB\\nAndroid" | dmenu -l $menu_alto_lineas -w $menu_ancho -x $XX -y $YY -i -p "¿Desmontar una unidad USB o un dispositivo Android?")" || exit 1
	case "$choice" in
		USB) unmountusb ;;
		Android) unmountandroid ;;
	esac
	}

drives=$(lsblk -nrpo "name,type,size,mountpoint" | awk '$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s (%s)\n",$4,$3}')

if ! grep simple-mtpfs /etc/mtab; then
	[ -z "$drives" ] && echo "No hay unidades para desmontar." &&  exit
	echo "Se detectó una unidad USB que no se puede montar."
	unmountusb
else
	if [ -z "$drives" ]
	then
		echo "Se detectó un dispositivo Android que no se puede montar."
	       	unmountandroid
	else
		echo "Se detectaron unidades USB y dispositivos Android que no se pueden montar."
		asktype
	fi
fi
