#!/bin/sh

#DEFINIR ANCHO Y NUMERO DE LINEAS HORIZONTALES
menu_alto_lineas=10
menu_ancho=350
#MEDIDAS DE MONITOR NO TOCAR
monitor_ancho=$(cat /tmp/resoluciones | awk 'NR==2 {print}')
monitor_alto=$(cat /tmp/resoluciones | awk 'NR==3 {print}')
#ALINEAR A LA DERECHA ARRIBA
#XX=$(( $monitor_ancho - $menu_ancho -0 ))
#YY=$(( 25 ))
#ALINEADO A LA IZQUIERA ARRIBA
XX=0
YY=25
#ALINEADO AL CENTRO
#menu_alto_pixeles=$(( $menu_alto_lineas * 10 ))
#menu_mitad_ancho=$(( $menu_ancho / 2 ))
#XX=$(( $monitor_ancho / 2 - $menu_mitad_ancho ))
#YY=$(( $monitor_alto / 2 - $menu_alto_pixeles ))

prompt() { \
  choice=$(printf "Screencast\nSolo video\nSolo audio\nWebcam flotante\nGrabar webcam\nDetener grabacion" |dmenu -l $menu_alto_lineas -w $menu_ancho -x $XX -y $YY -p "Seleccionar el tipo de grabacion: ")
  case $choice in 
    "Screencast") screencast;;
    "Solo video") video;;
    "Solo audio") audio;;
    "Webcam flotante") webcamflotante;;
    "Grabar webcam") webcam;;
    "Detener grabacion") detener;;
  esac
}

screencast() { \
  ffmpeg -y \
  -f x11grab \
  -framerate 60 \
  -s "$(xdpyinfo | grep dimensions | awk '{print $2;}')" \
  -i "$DISPLAY" \
  -f alsa -i default \
  -r 60 \
  -c:v h264 -crf 0 -preset ultrafast -c:a aac \
  "$HOME/grabacion-$(date '+%y%m%d-%H%M-%S').mp4" &
  echo $! > /tmp/recordingpid
}

video() { ffmpeg \
  -f x11grab \
  -s "$(xdpyinfo | grep dimensions | awk '{print $2;}')" \
  -i "$DISPLAY" \
  -c:v libx264 -qp 0 -r 60 \
  "$HOME/video-$(date '+%y%m%d-%H%M-%S').mkv" &
  echo $! > /tmp/recordingpid
}

audio() { \
  ffmpeg \
  -f alsa -i default \
  -c:a flac \
  "$HOME/audio-$(date '+%y%m%d-%H%M-%S').flac" &
  echo $! > /tmp/recordingpid
}

webcamflotante() { \
  pkill -f /dev/video || mpv --no-osc --no-input-default-bindings --input-conf=/dev/null --geometry=-0-0 --autofit=20%  --title="mpvfloat" /dev/video0 
  echo $! > /tmp/recordingpid
}

webcam() { ffmpeg \
  -f v4l2 \
  -i /dev/video0 \
  -video_size 1920x1080 \
  "$HOME/webcam-$(date '+%y%m%d-%H%M-%S').mkv" &
  echo $! > /tmp/recordingpid
}

detener() { \
  killall ffmpeg > /dev/null 2>&1
  rm -f /tmp/recording_pid
}

case "$1" in 
  "Screencast") screencast;;
  "Solo video") video;;
  "Solo audio") audio;;
  "Webcam flotante") webcamflotante;;
  "Grabar webcam") webcam;;
  "Detener grabacion") detener;;
  *)  ([ -f /tmp/recording_pid ] && exit 1) || prompt;;
esac