#!/bin/sh

#DEFINIR ANCHO Y NUMERO DE LINEAS HORIZONTALES
menu_alto_lineas=10
menu_ancho=400
#MEDIDAS DE MONITOR NO TOCAR
monitor_ancho=$(cat /tmp/resoluciones | awk 'NR==2 {print}')
monitor_alto=$(cat /tmp/resoluciones | awk 'NR==3 {print}')
#ALINEAR A LA DERECHA ARRIBA
XX=$(( $monitor_ancho - $menu_ancho - 2 ))
YY=$(( 25 ))
#ALINEADO A LA IZQUIERA ARRIBA
#XX=0
#YY=25
#ALINEADO AL CENTRO
#menu_alto_pixeles=$(( $menu_alto_lineas * 10 ))
#menu_mitad_ancho=$(( $menu_ancho / 2 ))
#XX=$(( $monitor_ancho / 2 - $menu_mitad_ancho ))
#YY=$(( $monitor_alto / 2 - $menu_alto_pixeles ))

getmount() { \
	[ -z "$chosen" ] && exit 1
        # shellcheck disable=SC2086
	mp="$(find $1 2>/dev/null | dmenu -l $menu_alto_lineas -w $menu_ancho -x $XX -y $YY -i -p "Escriba punto de montaje.")" || exit 1
	[ "$mp" = "" ] && exit 1
	if [ ! -d "$mp" ]; then
		mkdiryn=$(printf "No\\nYes" | dmenu -l $menu_alto_lineas -w $menu_ancho -x $XX -y $YY -i -p "$mp no existe. ¿Crearlo?") || exit 1
		[ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
	fi
	}

mountusb() { \
	chosen="$(echo "$usbdrives" | dmenu -l $menu_alto_lineas -w $menu_ancho -x $XX -y $YY -i -p "¿Que unidad desea montar?")" || exit 1
	chosen="$(echo "$chosen" | awk '{print $1}')"
	sudo -A mount "$chosen" 2>/dev/null && notify-send "💻 USB Montado" "$chosen montada." && exit 0
	alreadymounted=$(lsblk -nrpo "name,type,mountpoint" | awk '$3!~/\/boot|\/home$|SWAP/&&length($3)>1{printf "-not ( -path *%s -prune ) ",$3}')
	getmount "/mnt /media /mount /home -maxdepth 5 -type d $alreadymounted"
	partitiontype="$(lsblk -no "fstype" "$chosen")"
	case "$partitiontype" in
		"vfat") sudo -A mount -t vfat "$chosen" "$mp" -o rw,umask=0000;;
		*) sudo -A mount "$chosen" "$mp"; user="$(whoami)"; ug="$(groups | awk '{print $1}')"; sudo -A chown "$user":"$ug" "$mp";;
	esac
	notify-send "💻 USB Montado" "$chosen mounted to $mp."
	}

mountandroid() { \
	chosen="$(echo "$anddrives" | dmenu -l $menu_alto_lineas -w $menu_ancho -x $XX -y $YY -i -p "¿Qué dispositivo Android?")" || exit 1
	chosen="$(echo "$chosen" | cut -d : -f 1)"
	getmount "$HOME -maxdepth 3 -type d"
        simple-mtpfs --device "$chosen" "$mp"
	echo "OK" | dmenu -l $menu_alto_lineas -w $menu_ancho -x $XX -y $YY -i -p "Tap Allow on your phone if it asks for permission and then press enter" || exit 1
	simple-mtpfs --device "$chosen" "$mp"
	notify-send "🤖 Android Montado" "Android device mounted to $mp."
	}

asktype() { \
	choice="$(printf "USB\\nAndroid" | dmenu -l $menu_alto_lineas -w 350 -x 0 -y 25 -i -p "¿Montar una unidad USB o un dispositivo Android?")" || exit 1
	case $choice in
		USB) mountusb ;;
		Android) mountandroid ;;
	esac
	}

anddrives=$(simple-mtpfs -l 2>/dev/null)
usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | awk '$4==""{printf "%s (%s)\n",$1,$3}')"

if [ -z "$usbdrives" ]; then
	[ -z "$anddrives" ] && echo "No se detectó ninguna unidad USB o dispositivo Android" && exit
	echo "Dispositivo (s) Android detectado."
	mountandroid
else
	if [ -z "$anddrives" ]; then
		echo "Se detectaron unidades USB.."
		mountusb
	else
		echo "Se detectaron unidades USB montables y dispositivos Android."
		asktype
	fi
fi
