#!/usr/bin/env bash

. "${HOME}/.cache/wal/colors.sh"

monitor_ancho=$(cat /tmp/resoluciones | awk 'NR==2 {print}')
ancho_notificacion=350
YY=25
mitad_ancho_notificacion=$(($ancho_notificacion / 2 ))
XX=$(( $monitor_ancho / 2 - $mitad_ancho_notificacion ))

  reload_dunst() {
    pkill dunst
    dunst \
    	-geom 350x5-$XX+$YY \
  		-frame_width 1 \
        -frame_color "${color2}" \
        -lf "${color7}" \
        -bf "${color7}" \
        -cf "${color7}" \
        -nf "${color7}" &
}
reload_dunst