#!/bin/sh

#DEFINIR ANCHO Y NUMERO DE LINEAS HORIZONTALES
menu_alto_lineas=10
menu_ancho=600
#MEDIDAS DE MONITOR NO TOCAR
monitor_ancho=$(cat /tmp/resoluciones | awk 'NR==2 {print}')
monitor_alto=$(cat /tmp/resoluciones | awk 'NR==3 {print}')
#ALINEAR A LA DERECHA ARRIBA
#XX=$(( $monitor_ancho - $menu_ancho -5 ))
#YY=$(( 25 ))
#ALINEADO A LA IZQUIERA ARRIBA
#XX=0
#YY=25
#ALINEADO AL CENTRO
menu_alto_pixeles=$(( $menu_alto_lineas * 10 ))
menu_mitad_ancho=$(( $menu_ancho / 2 ))
XX=$(( $monitor_ancho / 2 - $menu_mitad_ancho ))
YY=$(( $monitor_alto / 2 - $menu_alto_pixeles ))


url=""
quality=""
arguments=""
helperPath=`dirname "$0"`

#Function for getting arguments for the downloader
providearguments(){
	arguments=`echo -e 'Si\nNo' |dmenu -l $menu_alto_lineas -w $menu_ancho -x $XX -y $YY -i -fn 'sf compact text:bold:size=9' -p "Ya tenemos el formato. Desea descargar?"`
	[[ $arguments = "" ]] && exit 0
}

#Function to select url from clipboard.
#greenclip is here a clipboard manager.
selecturl(){
	url=`xclip -o -selection c print| xargs -0 | $helperPath/extract |dmenu -i -l $menu_alto_lineas -w $menu_ancho -x $XX -y $YY -fn 'sf compact text:bold:size=9' -p "MPV/YOUTUBE-DL: Esta es la URL del video?"`
	[[ $url = "" ]] && exit 0
}

#function to use youtube-dl to fetch quality of videos.
selectquality(){
	quality=`notify-send "Espere" "Buscando formatos disponibles..." | youtube-dl -F $url | \
	sed -n '7,50p' | \
	dmenu -l $menu_alto_lineas -w $menu_ancho -x $XX -y $YY -i -fn 'sf compact text:bold:size=9' -p "Seleccione el formato y/o calidad:" | \
	awk '{print $1;}'`
	[[ $quality = "" ]] && exit 0
}

main(){
	selecturl
	selectquality
	providearguments
	quality=`echo $quality | sed 's/ /+/'`
	if [[ $arguments = "No" ]]
		then
		mpv $url
	else
		echo "$arguments"
		youtube-dl -f $quality $url
	fi
}

main
